config/routes.rb
Rails.application.routes.draw do

    root "sessions#new"

    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    match '/signup',  to: 'users#new',            via: 'get'
    match '/login',  to: 'sessions#new',         via: 'get'
    match '/logout',  to: 'sessions#destroy',     via: 'delete'

    resources :runs
    resources :tracks

    get 'gpx' => 'gpx#new'
    post 'gpx' => 'gpx#create'

    get 'statistics' => 'statistics#index'
end

app/models/run.rb
class Run < ActiveRecord::Base
	validates :datetime, presence: true, uniqueness: true
    validates :distance, presence: true
  	validates :duration, presence: true
  	validates :velocity_average, presence: true
    validates :pace_average, presence: true
    
	serialize :points, Array
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
    def index
        @last_run = Run.where(:UserID => current_user[:id]).order(datetime: :desc)
        @runs = Run.where(:UserID => current_user[:id]).order(datetime: :desc)
    end

    def show
        @run = Run.find(params[:id])
        @runs = Run.all
    end

    def new
    	@run = Run.new
    end

    def create
    	day = params[:run]["datetime(3i)"]
    	month = params[:run]["datetime(2i)"]
    	year = params[:run]["datetime(1i)"]
    	hour = params[:run]["datetime(4i)"]
    	minute = params[:run]["datetime(5i)"]
    	datetime = Time.parse(day + "." + month + "." + year + " " + hour + ":" + minute)
    	r = Run.create({:datetime => datetime, :distance => params[:run][:distance], :duration => params[:run][:duration], :velocity_average => params[:run][:velocity_average], :pace_average => params[:run][:pace_average], :points => session[:points], :UserID => current_user[:id], :temperatur => params[:run][:temperatur], :wetter => params[:run][:wetter]})
    	#reset_session
        if r.save
            session[:datetime] = Time.now
            session[:distance] = ""
            session[:duration] = ""
            session[:velocity_average] = ""
            session[:pace_average] = ""
            session[:points] = ""
            session[:temperatur] = ""
            session[:wetter] = ""
    	   redirect_to "/runs"
        else
            flash[r.errors.messages] = r.errors.messages
            redirect_to controller: "runs", action: "new"
        end
    end

    def edit
    	@run = Run.find(params[:id])
    end

    def update
    	run = Run.find(params[:id])
		day = params[:run]["datetime(3i)"]
    	month = params[:run]["datetime(2i)"]
    	year = params[:run]["datetime(1i)"]
    	hour = params[:run]["datetime(4i)"]
    	minute = params[:run]["datetime(5i)"]
    	datetime = Time.parse(day + "." + month + "." + year + " " + hour + ":" + minute)
    	Run.update_all({:datetime => datetime, :distance => params[:run][:distance], :duration => params[:run][:duration], :velocity_average => params[:run][:velocity_average], :pace_average => params[:run][:pace_average]})
    	redirect_to controller: "runs", action: "show", id: params[:id]
    end

    def destroy
    	run = Run.find(params[:id])
    	run.destroy
    	redirect_to controller: "runs"
    end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/edit.html.erb
<div class="row">
<script src="../../js/edit.js"></script>
  <div class="col-md-4">
  <div><%= form_for @run do |f| %></div>
  <div><%= f.label :datetime %><%= f.datetime_select :datetime, { :default => session[:datetime]}, class: "datetime_input"  %></div>
  <div><%= f.label :duration %><%= f.text_field :duration, :value => @run.duration, class: "duration_input" %></div>
  <div><%= f.label :velocity_average, "Velocity" %><%= f.text_field :velocity_average, :value => @run.velocity_average, class: "velocity_input" %></div>
  <div><%= f.label :pace_average, "Pace" %><%= f.text_field :pace_average, :value => @run.pace_average, class: "pace_input" %></div>
  <div><%= f.label :note%><%= f.text_field :note%></div>
  <div><%= f.label :feeling%><%= f.text_field :feeling%></div>
  <%= f.submit "Edit Run" %>
  <% end %>
  <%= button_to "delete", @run, :method=>:delete, :class=>:destroy %>
  </div>
  
  <div class="col-md-1"></div>
  <div class="col-md-5"><div id='map'><script type="text/javascript">initmap(<%=@run.points%>, 'map');</script></div></div>
</div>

app/views/runs/index.html.erb
<h4>Hey <%= current_user.name %>, your runs:</h4>

<%- Date.today.downto(Date.today - 31.days) do |date| %>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <span style="font-size: small; color: grey"><%= date.strftime("%d.%m.%Y") %></span>
        </div>
        <% @runs.each do |run| %>
             <% if run.datetime.strftime("%d.%m.%Y") == date.strftime("%d.%m.%Y") %>
                <div class="col-md-2">
                    <%= link_to "Run!", controller: "runs", action: "show", id: run.id %><br/>
                    Distance: <%= (run.distance.to_f / 1000).round(2).to_s %> km.<br/>
                    Duration: <%= run.duration.to_f.round(2).to_s %> min.
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-2">
                    <div class="ddd<%= run.datetime.strftime('%d') %>"></div>
                    <% radius = run.distance * 50 / 10000 %>
                    <script>//Make an SVG Container
                    var svgContainer = d3.select(".ddd<%= run.datetime.strftime('%d') %>").append("svg")
                                            .attr("width", 150)
                                            .attr("height", 150);
 
                    //Draw the Circle
                    var circle = svgContainer.append("circle")
                                                .attr("cx", 60)
                                                .attr("cy", 60)
                                                .attr("r", <%= radius %>)
                                                .attr("style", "fill: #E6521E");
                    </script>
                </div>
            <% end %>
        <% end %>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <hr/>
    </div>
<%- end %>

app/views/runs/new.html.erb
<div class="row">
<script src="../../js/edit.js"></script>
  <div class="col-md-4">
  <div><%= link_to "Upload a Gpx", gpx_path %><br/>
      <%= link_to "Choose a Track", tracks_path %>
      <%= form_for @run do |f| %></div>
        <div><%= f.label :datetime %><%= f.datetime_select :datetime, { :default => session[:datetime]}, class: "datetime_input"  %></div>
        <div><%= f.label :distance %><%= f.text_field :distance, :value => session[:distance].to_f.round(2).to_s, class: "distance_input" %></div>
        <div><%= f.label :duration %><%= f.text_field :duration, :value => session[:duration], class: "duration_input" %></div>
        <div><%= f.label :velocity_average, "Velocity" %><%= f.text_field :velocity_average, :value => session[:velocity_average].to_f.round(2).to_s, class: "velocity_input" %></div>
        <div><%= f.label :pace_average, "Pace" %><%= f.text_field :pace_average, :value => session[:pace_average].to_f.round(2).to_s, class: "pace_input" %></div>
        <div><%= f.label :note%><%= f.text_field :note%></div>
        <div><%= f.label :feeling%><%= f.text_field :feeling%></div>
        <div><%= f.label :temperatur%><%= f.text_field :temperatur, :value => session[:temperatur]%></div>
        <div><%= f.label :wetter%><%= f.text_field :wetter, :value => session[:wetter]%></div>
        <%= f.submit "Create Run" %>
      <% end %>
  </div>
  <div class="col-md-1"></div>
  <div class="col-md-5"><div id='map'><script type="text/javascript">initmap(<%=session[:points]%>, 'map');</script></div></div>
</div>

app/views/runs/show.html.erb
<div class="row">
    <div class="col-md-4">
 <h4>Your run on <span id='last_date'><%= @run.datetime.strftime("%d.%m.%y, beginning at %k:%M") %></span>:</h4> You ran a distance of <b><span id='last_distance'><%= (@run.distance.to_f / 1000).round(2).to_s %></span> km.</b> in <b><span id='last_length'><%= @run.duration.to_f.round(2).to_s %></span> min.</b> That makes for an average speed of <b><span id='last_geschdurchschnitt'><%= @run.velocity_average.to_f.round(2).to_s %></span> km/h</b> and an average pace of <b><span id='last_pacedurchschnitt'><%= @run.pace_average.to_f.round(2).to_s %></span> min/km.</b> The temperatur on this day was <%= @run.temperatur %> °C, the weather condition was <%= @run.wetter %>.

 <br/><br/>
 <%= link_to "Edit Run", controller: "runs", action: "edit", id: @run %><br/>
        <% session[:points] = @run.points %>
        <% session[:distance] = @run.distance %>
 <%= link_to "Save Track", controller: "tracks", action: "new"%>
    </div>

    <div class="col-md-3"></div>
    <div class="col-md-5">
    <div id='map'><script type="text/javascript">initmap(<%=@run.points%>, 'map');</script></div>
    </div></div>
<div class="row" style="height: 50px;"></div>