config/routes.rb
Rails.application.routes.draw do

    root "sessions#new"

    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    match '/signup',  to: 'users#new',            via: 'get'
    match '/login',  to: 'sessions#new',         via: 'get'
    match '/logout',  to: 'sessions#destroy',     via: 'delete'

    resources :runs
    resources :tracks

    get 'gpx' => 'gpx#new'
    post 'gpx' => 'gpx#create'

    get 'statistics' => 'statistics#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Rapp. The open source running app</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Bootstrap -->
		<link href="/css/lib/bootstrap.css" rel="stylesheet">
		<link href="/css/bootstrap-custom.css" rel="stylesheet">
        
        
        <script language="javascript" type="text/javascript" src="/js/lib/jquery-2.1.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lib/jquery_ujs.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lib/leaflet.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lib/leaflet-omnivore.min.js"></script>
        <script language="javascript" type="text/javascript" src="/js/map.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lib/leaflet-editable-polyline.js"></script>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link rel="stylesheet" type="text/css" href="/css/lib/leaflet.css">
        
        <link rel='stylesheet' href='/css/lib/fullcalendar.css' />
        <link href="/css/fullcalendar-custom.css" rel="stylesheet">
        <script src='/js/lib/moment.min.js'></script>
        <script language="javascript" type="text/javascript" src="/js/lib/fullcalendar.js"></script>
        
        <script src="/js/lib/highcharts.js"></script>
        <script src="/js/lib/d3.js" charset="utf-8"></script>

        <!--<%= javascript_include_tag "application" %>-->
        <%= csrf_meta_tag %> 


		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="container">

			<!-- Static navbar -->
			<nav class="navbar navbar-default" role="navigation">
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			      <span class="sr-only">Toggle navigation</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <a class="navbar-brand" href="/runs">Rapp</a>
			  </div>
			  <div class="navbar-collapse collapse">
			    <ul class="nav navbar-nav">
			      <li><a href="/runs/new">New Run</a></li>
			      <li><a href="/statistics">Statistics</a></li>
			    </ul>
          		<% if logged_in? %>
          			<ul class="nav navbar-nav navbar-right">
            		<li><%= link_to "Users", '#' %></li>
            		<li class="dropdown">
              		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              		<ul class="dropdown-menu">
                		<li><%= link_to "Profile", current_user %></li>
                		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
                		<li class="divider"></li>
                		<li>
                  			<%= link_to "Sign out", logout_path, method: "delete" %>
                		</li>
              		</ul>
            		</li>
            		</ul>
          		<% else %>
            		<ul class="nav navbar-nav navbar-right">
            		<li><%= link_to "Sign in", login_path %></li>
            		</ul>
          		<% end %>
			  </div><!--/.nav-collapse -->
			</nav>

			<div>
                <%if @error then %>
			          <div class="alert alert-error"><%=@error%></div>
			    <% end %>
			    <% flash.each do |key, value| %>
        			<div class="alert alert-<%= key %>"><%= value %></div>
      			<% end %>
			      <%= yield %>
			</div>
			<%= debug(params) if Rails.env.development? %>
		</div>

    	<!-- Include all compiled plugins (below), or include individual files as needed -->
    	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
 	 </body>
</html>

app/views/layouts/not_logged_in.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Rapp. The open source running app</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Bootstrap -->
		<link href="/css/lib/bootstrap.css" rel="stylesheet">
		<link href="/css/bootstrap-custom.css" rel="stylesheet">
        
        
        <script language="javascript" type="text/javascript" src="/js/lib/jquery-2.1.1.min.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lib/jquery_ujs.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lib/leaflet.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lib/leaflet-omnivore.min.js"></script>
        <script language="javascript" type="text/javascript" src="/js/map.js"></script>
        <script language="javascript" type="text/javascript" src="/js/lib/leaflet-editable-polyline.js"></script>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
        <link rel="stylesheet" type="text/css" href="/css/lib/leaflet.css">
        
        <link rel='stylesheet' href='/css/lib/fullcalendar.css' />
        <link href="/css/fullcalendar-custom.css" rel="stylesheet">
        <script src='/js/lib/moment.min.js'></script>
        <script language="javascript" type="text/javascript" src="/js/lib/fullcalendar.js"></script>
        
        <script src="/js/lib/highcharts.js"></script>

        <!--<%= javascript_include_tag "application" %>-->
        <%= csrf_meta_tag %> 


		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="container">

			<!-- Static navbar -->
			<nav class="navbar navbar-default" role="navigation">
			  
			</nav>

			<div>
                <%if @error then %>
			          <div class="alert alert-error"><%=@error%></div>
			    <% end %>
			    <% flash.each do |key, value| %>
        			<div class="alert alert-<%= key %>"><%= value %></div>
      			<% end %>
			      <%= yield %>
			</div>
			<%= debug(params) if Rails.env.development? %>
		</div>

    	<!-- Include all compiled plugins (below), or include individual files as needed -->
    	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
 	 </body>
</html>